# Generated by Django 6.0.9 on 2026-10-08 19:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    SecuritySettings = apps.get_model("accounts", "SecuritySettings")
    SecuritySettings.objects.get_or_create(
        pk=1,
        defaults={"email_otp_enabled": True, "sms_otp_enabled": False},
    )


def remove_default_settings(apps, schema_editor):
    SecuritySettings = apps.get_model("accounts", "SecuritySettings")
    SecuritySettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin_profile_and_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_otp_enabled', models.BooleanField(default=True)),
                ('sms_otp_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_settings, remove_default_settings),
        migrations.AddField(
            model_name='auditevent',
            name='detail',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('code_hash', models.CharField(blank=True, max_length=256)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
